### ISSUE TITLE
[Feature] Auth/User

### ISSUE THREAD

**Issue by dongkyeomjang** [9oormthon-univ/9oormthon-uninv-server#13]
## 🛠 Issue

Auth API 구현,
User API 구현

## 📝 To-do

- [ ] User Entity 구현
- [ ] User Entity 구현에 따른 포맷 셋팅
- [ ] Auth 관련 API 구현(회원가입,로그인, 인증 및 인가, 비밀번호 재설정)
- [ ] User Api 구현
