### ISSUE TITLE
[Feat] Univ CRUD 구현

### ISSUE THREAD

**Issue by dongkyeomjang** [9oormthon-univ/9oormthon-uninv-server#8]
## 🛠 Issue

Univ CRUD API를 구현한다.
## 📝 To-do

- [ ] Univ 전체 리스트 조회 API 
- [ ] Univ 조회 specification API
- [ ] Univ 생성 API(관리자용)
- [ ] Univ 삭제 API(관리자용)
- [ ] Univ 수정 API(관리자용)
